### ISSUE TITLE
Remove duplicate word from log file

### ISSUE THREAD

**Issue by sayanmondal2098** [Bread-and-Code/nltk-based-word-checking-dic-method#14]
With help of the "finder.py" script we can create log file . But in the files there are few duplicate words . or a same word few many time . Need help to remove the duplicates .

**Comment by sayanmondal2098** [comment]
we have positive word dictionary,negative word dictionary and a text file(with paragraphs). we have to write a program to tokenize key words from the text file . Then match those key words with positive and negative file. if the key word is matched with any of these file the store it in destinationposfile or destinationneg file. If the key word is not found then collect synonyms of that key word and again try to match those words with positive or negative file , if match found then store that key word in a destination file and if not found then store that key word in destinationnutral file.

**Comment by rra94** [comment]
I can take this.
The issue is to remove duplicate words in the log.txt file right?

**Comment by sayanmondal2098** [comment]
Sure , go for it . There are 3 log file (destinationposfile.txt, destinationnegfile.txt and destinationposfile.txt).
Thanks

**Comment by rra94** [comment]
Why do you have trie here instead of a simple list?
