### ISSUE TITLE
Add a word picker feature 

### ISSUE THREAD

**Issue by sayanmondal2098** [Bread-and-Code/nltk-based-word-checking-dic-method#8]
we have positive word dictionary,negative word dictionary and a text  file(with paragraphs). we have to write a program to tokenize key words from the text file . Then match those key words with positive and negative file. if the key word is  matched with any of these file the store it in destinationposfile or destinationneg file. If the key word is not found then collect synonyms of that key word and again try to match those words with positive or negative file , if match found then store that key word in a destination file and if not found then store that key word in destinationnutral file.

**Comment by AbhiAgarwal192** [comment]
@sayanmondal2098 Can i work on this?

**Comment by sayanmondal2098** [comment]
Sure :) go for it. But please keep in mind that we need the exact word matching  feature . Thank you :)

**Comment by AbhiAgarwal192** [comment]
So the requirement is that the script will scan each word in the text file and check?

**Comment by sayanmondal2098** [comment]
Yea , and check word from a text file with the  "list of negative words.txt" and "list of negative words.txt " dictionary . If a word exact match , then separate them and log them into two different text file names "destinationnegfile.txt" and "destinationnegfile.txt"

**Comment by MahikanthNag** [comment]
hey,
can you give me some specifics about from which file we have to pick the word in order to check that word in the files "list of negative words.txt" and "list of positive words.txt". 
According to my understanding, we need to pick a word from some file and check for its precense in the above mentioned 2 files and log it in destination files. am i right? I am just thinking about what that "some" file can be. 
Thank You :)

**Comment by sayanmondal2098** [comment]
@MahikanthNag  yea you are right. The source file is a textfile .  And log them into two different files as (if the word is  a positive one then log into positive_destination_file    and if the word is negative then log into negative_destination_file) .

**Comment by Anik101** [comment]
we have positive word dictionary,negative word dictionary and a text file(with paragraphs). we have to write a program to tokenize key words from the text file . Then match those key words with positive and negative file. if the key word is matched with any of these file the store it in destinationposfile or destinationneg file. If the key word is not found then collect synonyms of that key word and again try to match those words with positive or negative file , if match found then store that key word in a destination file and if not found then store that key word in destinationnutral file.
